Fixes for overlap check in config validation
With this, the config validation now properly detects the dupe that was
fixed earlier in commit a8c7f008066e7a7980b.

With that one reverted, the failure looks like this:

=== RUN   TestConfigs
    config_test.go:47: main+4.13 combined config failed validation: errors: <nil>; warnings: config entry [[rpm.containernetworking-plugins.ignore]].error=ErrGoMissingTag.files contains a redundant path "/usr/libexec/cni/dummy", overlapped by "/usr/libexec/cni"
--- FAIL: TestConfigs (0.00s)

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>