feat: ensure the config is fully parsed
Return an error otherwise.

This actually helped to find an error in 4.9 config (which is fixed).
Before the fix, the error looked like this:

> Error: unknown keys in config: [node."podman-catatonit-3.2.3-0.12.module+el8.4.0+14908+81312c48.x86_64".filter_images]

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>